[package]
name = "quantum-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "quantum"
path = "src/main.rs"

[dependencies]
quantum-core = { path = "../quantum-core" }
quantum-jit = { path = "../quantum-jit" }
quantum-kernel32 = { path = "../quantum-kernel32" }
quantum-loader = { path = "../quantum-loader" }
quantum-runtime = { path = "../quantum-runtime" }

[lints]
workspace = true
