[package]
name = "quantum-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "quantum"
path = "src/main.rs"

[dependencies]
quantum-core = { path = "../quantum-core" }
quantum-loader = { path = "../quantum-loader" }

[lints]
workspace = true
